### ISSUE TITLE
Parameters tied in ELMo model

### ISSUE THREAD

**Issue by nanguoshun** [RaleighZ/statnlp_fundamental_reading#5]

**Comment by RaleighZ** [comment]
In the original ELMo paper, authors mention that "We tie the parameters for both the token representation (Θx) and Softmax layer (Θs) in the forward and backward direction while maintaining separate parameters for the LSTMs in each direction."

I think parameters for Softmax layer is the projection matrix  (hidden_dim * # of class) before classification. And parameters for tokens representation maybe the parameters in Char-CNN, which is used to generate the representation for each input tokens. 

And it's reasonable to tie these parameters in the model.

**Comment by Cartus** [comment]
Yes, I agree.
